import ConformPageComponent from "@/components/payment/ConformPaymentComponent";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Payment-Donor App",
  description: "Generated by create next app",
};
const ConformPage = () => {
  return (
    <div>
      <ConformPageComponent />
    </div>
  );
};

export default ConformPage;
