import Registration from "@/components/ui/Registration";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Donor App | Registration",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className=" mt-10  max-w-7xl mx-auto px-4 lg:px-0">
      <Registration />
    </div>
  );
};

export default page;
