import SuccessPageComponent from "@/components/payment/SuccessPageComponent";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Success - Health Care",
  description: "Generated by create next app",
};
const SuccessPage = () => {
  return (
    <div>
      <SuccessPageComponent />
    </div>
  );
};

export default SuccessPage;
