import DonorComponents from "@/components/bloodDonor/DonorsComponents";
import NoData from "@/components/ui/NoData";
import { URL } from "@/constants/common";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Donor App | Donors",
  description: "Generated by create next app",
};
interface SearchParams {
  bloodGroup: string;
  division: string;
  district: string;
}

const FindingDonorPage = async ({
  searchParams,
}: {
  searchParams: SearchParams;
}) => {
  const res = await fetch(
    `${URL}/blood-donor?sub_district=${searchParams.district}&district=${searchParams.division}&blood_group=${searchParams.bloodGroup}`,
    {
      cache: "no-cache",
    }
  );
  const data = await res.json();

  return (
    <div className="max-w-7xl mx-auto px-4 lg:px-0 mt-28">
      {data?.data.length === 0 && <NoData />}
      <DonorComponents donors={data?.data} />
    </div>
  );
};

export default FindingDonorPage;
