import ServiceCategoryComponent from "@/components/doctorService/ServiceCategory";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Donor App | Service Category",
  description: "Generated by create next app",
};
const ServiceCategoryPage = ({
  params,
  searchParams,
}: {
  params: any;
  searchParams: { name: string };
}) => {
  return (
    <div>
      <ServiceCategoryComponent searchParams={searchParams} />
    </div>
  );
};

export default ServiceCategoryPage;
