import FindDoctor from "@/components/doctor/FindDoctor";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Donor App | Find Doctor & Service",
  description: "Generated by create next app",
};
const FindDoctorPage = () => {
  return (
    <div className=" max-w-7xl mx-auto px-4 lg:px-0 mt-28">
      <FindDoctor />
    </div>
  );
};

export default FindDoctorPage;
