import PaymentPageComponent from "@/components/payment/PaymentPageComponent";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Patient Info-Donor App",
  description: "Generated by create next app",
};
const AppointmentBookingForm = () => {
  return (
    <div>
      <PaymentPageComponent />
    </div>
  );
};

export default AppointmentBookingForm;
