import AllNotification from "@/components/notification/AllNotificaiton";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Notification-Donor App",
  description: "Generated by create next app",
};
const Notification = () => {
  return (
    <div className="px-4">
      <div className=" max-w-4xl   lg:px-0 border  h-full mx-auto my-28">
        <AllNotification />
      </div>
    </div>
  );
};

export default Notification;
