import DoctorDetails from "@/components/doctor/DoctorDetails";
import { URL } from "@/constants/common";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Details-Donor App",
  description: "Generated by create next app",
};
const DoctorDetailsPage = async ({ params }: { params: { id: string } }) => {
  const res = await fetch(`${URL}/user/${params.id}`, {
    cache: "no-cache",
  });
  const doctor = await res.json();
  // console.log(doctor);
  return (
    <div>
      <DoctorDetails doctor={doctor?.data}></DoctorDetails>
    </div>
  );
};

export default DoctorDetailsPage;
