import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/lib/Providers";

// import Header from "@/components/shared/Header";

// import Footer from "@/components/shared/Footer";
// import DashboardLayout from "../(rootLayout)/(dashboardLayout)/layout";
import SocialMediaNavbar from "@/components/shared/SocialMediaNavber";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blood Media - Health Care",
  description: "Generated by create next app",
};

export default function MediaLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <SocialMediaNavbar />

      {children}
    </div>
  );
}
