import SearchDonor from "@/components/bloodDonor/SearchDonor";

import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Donor App | Donor Reg",
  description: "Generated by create next app",
};
const BloodDonorPage = () => {
  return (
    <div className="">
      <SearchDonor />
    </div>
  );
};

export default BloodDonorPage;
